spring.application.name=spring-data-jpa-demo1
spring.profiles.active=dev
#เติมเพื่อปิดการทำงานของ web server เมื่อรัน Spring Boot Application แบบ Command Line Application
#spring.main.web-application-type=none
spring.threads.virtual.enabled=true
logging.config=config/logback-spring.xml
